import { useState } from 'react';
import { Pressable, SafeAreaView, StyleSheet, Text, TextInput, View } from 'react-native';
export default function MobileHome() {
  const [account, setAccount] = useState('Conta principal');
  const [message, setMessage] = useState('Use este app para consultar e revisar suas operações.');
  return <SafeAreaView style={styles.page}><View style={styles.header}><Text style={styles.eyebrow}>TRADE LOG</Text><Text style={styles.title}>TraderLab</Text><Text style={styles.subtitle}>A mesma conta e operações do seu ambiente web.</Text></View><View style={styles.card}><Text style={styles.heading}>Conta operacional</Text><TextInput value={account} onChangeText={setAccount} style={styles.input} /><Pressable style={styles.button} onPress={() => setMessage(`Conta “${account}” pronta para sincronizar com a API.`)}><Text style={styles.buttonText}>Salvar conta</Text></Pressable></View><View style={styles.card}><Text style={styles.heading}>Importar Profit</Text><Text style={styles.body}>No build nativo, o seletor de arquivos enviará os CSVs ao mesmo lote da API. O parser e a revisão permanecem no servidor.</Text><Pressable style={styles.secondary} onPress={() => setMessage('Seleção de arquivos será ativada com Expo DocumentPicker no próximo build nativo.')}><Text style={styles.secondaryText}>Selecionar CSVs</Text></Pressable></View><Text style={styles.notice}>{message}</Text></SafeAreaView>;
}
const styles = StyleSheet.create({ page:{flex:1,backgroundColor:'#f8fafc',padding:20},header:{paddingVertical:30},eyebrow:{color:'#4f46e5',fontWeight:'800',letterSpacing:1.5,fontSize:12},title:{fontSize:38,fontWeight:'800',color:'#111827',marginTop:6},subtitle:{color:'#64748b',fontSize:16,marginTop:8,lineHeight:24},card:{backgroundColor:'#fff',borderRadius:14,padding:18,marginBottom:14,borderWidth:1,borderColor:'#e2e8f0'},heading:{fontSize:18,fontWeight:'700',marginBottom:10},body:{color:'#64748b',lineHeight:21},input:{borderWidth:1,borderColor:'#cbd5e1',borderRadius:8,padding:11,marginBottom:10},button:{backgroundColor:'#4f46e5',borderRadius:8,padding:12,alignItems:'center'},buttonText:{color:'#fff',fontWeight:'700'},secondary:{borderWidth:1,borderColor:'#c7d2fe',borderRadius:8,padding:12,alignItems:'center',marginTop:10},secondaryText:{color:'#4338ca',fontWeight:'700'},notice:{color:'#475569',padding:12,textAlign:'center'} });

