BEGIN;

CREATE TEMP TABLE course_id_map (
  old_id TEXT PRIMARY KEY,
  new_id INTEGER GENERATED ALWAYS AS IDENTITY
) ON COMMIT DROP;
CREATE TEMP TABLE module_id_map (
  old_id TEXT PRIMARY KEY,
  new_id INTEGER GENERATED ALWAYS AS IDENTITY
) ON COMMIT DROP;
CREATE TEMP TABLE content_id_map (
  old_id TEXT PRIMARY KEY,
  new_id INTEGER GENERATED ALWAYS AS IDENTITY
) ON COMMIT DROP;
CREATE TEMP TABLE enrollment_id_map (
  old_id TEXT PRIMARY KEY,
  new_id INTEGER GENERATED ALWAYS AS IDENTITY
) ON COMMIT DROP;
CREATE TEMP TABLE progress_id_map (
  old_id TEXT PRIMARY KEY,
  new_id INTEGER GENERATED ALWAYS AS IDENTITY
) ON COMMIT DROP;

INSERT INTO course_id_map (old_id)
SELECT id FROM courses ORDER BY created_at, id;
INSERT INTO module_id_map (old_id)
SELECT id FROM course_modules ORDER BY created_at, id;
INSERT INTO content_id_map (old_id)
SELECT id FROM course_contents ORDER BY created_at, id;
INSERT INTO enrollment_id_map (old_id)
SELECT id FROM enrollments ORDER BY created_at, id;
INSERT INTO progress_id_map (old_id)
SELECT id FROM content_progress ORDER BY created_at, id;

ALTER TABLE courses
  ADD COLUMN id_new INTEGER GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE course_modules
  ADD COLUMN id_new INTEGER GENERATED BY DEFAULT AS IDENTITY,
  ADD COLUMN course_id_new INTEGER;
ALTER TABLE course_contents
  ADD COLUMN id_new INTEGER GENERATED BY DEFAULT AS IDENTITY,
  ADD COLUMN module_id_new INTEGER;
ALTER TABLE enrollments
  ADD COLUMN id_new INTEGER GENERATED BY DEFAULT AS IDENTITY,
  ADD COLUMN course_id_new INTEGER;
ALTER TABLE content_progress
  ADD COLUMN id_new INTEGER GENERATED BY DEFAULT AS IDENTITY,
  ADD COLUMN content_id_new INTEGER;

UPDATE courses AS t SET id_new = map.new_id
FROM course_id_map AS map WHERE t.id = map.old_id;
UPDATE course_modules AS t
SET id_new = map.new_id, course_id_new = course_map.new_id
FROM module_id_map AS map, course_id_map AS course_map
WHERE t.id = map.old_id AND t.course_id = course_map.old_id;
UPDATE course_contents AS t
SET id_new = map.new_id, module_id_new = module_map.new_id
FROM content_id_map AS map, module_id_map AS module_map
WHERE t.id = map.old_id AND t.module_id = module_map.old_id;
UPDATE enrollments AS t
SET id_new = map.new_id, course_id_new = course_map.new_id
FROM enrollment_id_map AS map, course_id_map AS course_map
WHERE t.id = map.old_id AND t.course_id = course_map.old_id;
UPDATE content_progress AS t
SET id_new = map.new_id, content_id_new = content_map.new_id
FROM progress_id_map AS map, content_id_map AS content_map
WHERE t.id = map.old_id AND t.content_id = content_map.old_id;

ALTER TABLE course_modules DROP CONSTRAINT course_modules_course_id_fkey;
ALTER TABLE course_contents DROP CONSTRAINT course_contents_module_id_fkey;
ALTER TABLE enrollments DROP CONSTRAINT enrollments_course_id_fkey;
ALTER TABLE content_progress DROP CONSTRAINT content_progress_content_id_fkey;

DROP INDEX enrollments_student_id_course_id_key;

ALTER TABLE courses DROP CONSTRAINT courses_pkey;
ALTER TABLE course_modules DROP CONSTRAINT course_modules_pkey;
ALTER TABLE course_contents DROP CONSTRAINT course_contents_pkey;
ALTER TABLE enrollments DROP CONSTRAINT enrollments_pkey;
ALTER TABLE content_progress DROP CONSTRAINT content_progress_pkey;

ALTER TABLE courses DROP COLUMN id;
ALTER TABLE course_modules DROP COLUMN id, DROP COLUMN course_id;
ALTER TABLE course_contents DROP COLUMN id, DROP COLUMN module_id;
ALTER TABLE enrollments DROP COLUMN id, DROP COLUMN course_id;
ALTER TABLE content_progress DROP COLUMN id, DROP COLUMN content_id;

ALTER TABLE courses RENAME COLUMN id_new TO id;
ALTER TABLE course_modules RENAME COLUMN id_new TO id;
ALTER TABLE course_modules RENAME COLUMN course_id_new TO course_id;
ALTER TABLE course_contents RENAME COLUMN id_new TO id;
ALTER TABLE course_contents RENAME COLUMN module_id_new TO module_id;
ALTER TABLE enrollments RENAME COLUMN id_new TO id;
ALTER TABLE enrollments RENAME COLUMN course_id_new TO course_id;
ALTER TABLE content_progress RENAME COLUMN id_new TO id;
ALTER TABLE content_progress RENAME COLUMN content_id_new TO content_id;

ALTER TABLE courses ADD CONSTRAINT courses_pkey PRIMARY KEY (id);
ALTER TABLE course_modules ADD CONSTRAINT course_modules_pkey PRIMARY KEY (id);
ALTER TABLE course_contents ADD CONSTRAINT course_contents_pkey PRIMARY KEY (id);
ALTER TABLE enrollments ADD CONSTRAINT enrollments_pkey PRIMARY KEY (id);
ALTER TABLE content_progress ADD CONSTRAINT content_progress_pkey PRIMARY KEY (id);

ALTER TABLE course_modules
  ADD CONSTRAINT course_modules_course_id_fkey
  FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE course_contents
  ADD CONSTRAINT course_contents_module_id_fkey
  FOREIGN KEY (module_id) REFERENCES course_modules(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE enrollments
  ADD CONSTRAINT enrollments_course_id_fkey
  FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE content_progress
  ADD CONSTRAINT content_progress_content_id_fkey
  FOREIGN KEY (content_id) REFERENCES course_contents(id) ON DELETE CASCADE ON UPDATE CASCADE;

CREATE INDEX course_modules_course_id_status_position_idx
  ON course_modules(course_id, status, position);
CREATE INDEX course_contents_module_id_status_position_idx
  ON course_contents(module_id, status, position);
CREATE UNIQUE INDEX enrollments_student_id_course_id_key
  ON enrollments(student_id, course_id);
CREATE INDEX enrollments_course_id_status_idx ON enrollments(course_id, status);
CREATE UNIQUE INDEX content_progress_student_id_content_id_key
  ON content_progress(student_id, content_id);

COMMIT;

